name: Convert Markdown 2 PDF
/home/runner/work/manual/manual/pdfs
on:
  push:
    branches:
      - master
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'weuweb02/src/**.md'
      - 'docs/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: weuweb02/src
          output_dir: weuweb02
          images_dir: weuweb02/images
          # for example <img src="./images/file-name.png">
          image_import: ./resources/img
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: weuweb02
