- name: PDF Paper Generator
  uses: rseng/pdf-generator@0.0.3
  with:        
   # The markdown file to render, path is relative to repository
   paper_markdown: README.md

   # The paper pdf to save
   paper_outfile: minimal.pdf

   # One of "minimal" or "pdf" for the template with image, etc.
   pdf_type: minimal
